#ifndef ERROR_CODE_H_
#define ERROR_CODE_H_

#ifndef ERROR_SUCCESS
#define ERROR_SUCCESS									0x0
#endif

#define SOCKET_ERROR_BASE							0x10000000
#define ERROR_SOCKET_CREATE						SOCKET_ERROR_BASE + 1
#define ERROR_SOCKET_INIT							SOCKET_ERROR_BASE + 2
#define ERROR_SET_SEND_BUFF						SOCKET_ERROR_BASE + 3
#define ERROR_SET_RECV_BUFF						SOCKET_ERROR_BASE + 4
#define ERROR_SET_REUSE_ADDR					SOCKET_ERROR_BASE + 5
#define ERROR_SET_LINGER								SOCKET_ERROR_BASE + 6
#define ERROR_SET_TCP									SOCKET_ERROR_BASE + 7
#define ERROR_SOCKET_CONNECT					SOCKET_ERROR_BASE + 8

#endif